# Generated by Django 3.2.7 on 2023-04-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('tag', models.CharField(max_length=11, verbose_name='标签')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
