# Generated by Django 3.2.7 on 2023-04-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiBoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('wuid', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='微博用户id')),
                ('access_token', models.CharField(max_length=32, verbose_name='微博的授权令牌')),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'user_weibo_profile',
            },
        ),
    ]
